server:
  port: 8040
spring:
  application:
    name: avi-ecom-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Avinash831999/avi-ecom-configs"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
